/**
 * Entry point. Registers BOTH integration modes:
 *  1. Button add-in on the report pages -> opens a full-screen overlay.
 *  2. Page add-in (standalone menu item) -> renders inline. Fallback for
 *     MyGeotab versions where the button hook isn't available.
 */
import { createRoot } from "react-dom/client";
import App from "./App.jsx";
import zenithCss from "./generated/zenith.css"; // generated by build.mjs (fonts stripped)
import customCss from "./styles.css";

/* global geotab */

const STYLE_ID = "rr-addin-styles";

function ensureStyles() {
    if (document.getElementById(STYLE_ID)) return;
    const style = document.createElement("style");
    style.id = STYLE_ID;
    style.textContent = zenithCss + "\n" + customCss;
    document.head.appendChild(style);
}

/* ------------------------- overlay (button) mode ------------------------- */

let overlay = null;
let overlayRoot = null;

function closeOverlay() {
    if (overlayRoot) {
        overlayRoot.unmount();
        overlayRoot = null;
    }
    if (overlay) {
        overlay.remove();
        overlay = null;
    }
}

function openOverlay(api) {
    if (overlay) return; // already open
    ensureStyles();
    overlay = document.createElement("div");
    overlay.className = "rr-overlay";
    const panel = document.createElement("div");
    panel.className = "rr-panel";
    overlay.appendChild(panel);
    overlay.addEventListener("click", e => {
        if (e.target === overlay) closeOverlay();
    });
    document.addEventListener("keydown", function esc(e) {
        if (e.key === "Escape") {
            closeOverlay();
            document.removeEventListener("keydown", esc);
        }
    });
    document.body.appendChild(overlay);
    overlayRoot = createRoot(panel);
    overlayRoot.render(<App api={api} mode="overlay" onClose={closeOverlay} />);
}

if (typeof geotab !== "undefined") {
    geotab.customButtons = geotab.customButtons || {};
    geotab.customButtons.showReportRecipients = function (event, api /*, state */) {
        openOverlay(api);
    };

    /* --------------------------- page add-in mode --------------------------- */

    geotab.addin = geotab.addin || {};
    geotab.addin.reportRecipients = function () {
        let root = null;
        let container = null;

        function mount(api) {
            if (!container) {
                container =
                    document.getElementById("reportRecipients-root") ||
                    document.getElementById("checkmateContent") ||
                    document.body;
            }
            ensureStyles();
            if (!root) {
                const host = document.createElement("div");
                host.className = "rr-page-host";
                container.appendChild(host);
                root = createRoot(host);
            }
            root.render(<App api={api} mode="page" />);
        }

        return {
            initialize(api, state, initializeCallback) {
                mount(api);
                initializeCallback();
            },
            focus(api) {
                mount(api);
            },
            blur() {
                /* keep state; nothing to tear down */
            }
        };
    };
}
